- hosts: servers
  vars:
    dbname: jspark
  tasks:

  - name: ensure apt cache is up to date
    apt: update_cache=yes
# ==============================================
# Installing Java
  - name: Install java 8 preresequesits
    apt: name=python-software-properties

  - name: Add Java 8 repository
    apt_repository: repo='ppa:webupd8team/java'

  - name: Agree to oracle license
    debconf: name=oracle-java8-installer question=shared/accepted-oracle-license-v1-1 vtype=select value=true

  - name: Install Java 8
    apt: name=oracle-java8-installer force=yes

  - name: Install Java 7 headless
    apt: name=openjdk-7-jre-headless force=yes
#===============================================
  - name: Install postgresql
    apt: name=postgresql

  - name: Check elasticsearch
    service:
      name: node1_elasticsearch
      state: started

  - name: Install pip
    apt: name=python-pip force=yes

  - name: Install python-dev
    apt: name=python-dev force=yes

  - name: Install postgresql-server-dev-all
    apt: name=postgresql-server-dev-all force=yes

  - name: Install psycopg2
    pip :
      name: psycopg2
  - name: Install postgresql
    apt:
      name: postgresql

#Has to login as user postgres
#Authentication method is peer
- hosts: servers
  become: yes
  become_user: postgres
  gather_facts: no
#has to change postgres config
  tasks:

  - name: postgresql_db create
    postgresql_db:
      name: yscholar

  - name: postgresql_user configure
    postgresql_user:
      name: yscholar
      password: secret

  - name: priv configure
    postgresql_privs:
      db: yscholar
      type: database
      privs: ALL
      roles: yscholar

#Install nginx
#TODO: Change hosts
- hosts: servers

  roles:
  - role: nginx
    nginx_sites:
      elasticsearch_yschola:
        template: nginx_template.j2
        server_port: 8888
        server_name: kscy.or.kr #TODO Change server_name
        proxy_pass: http://127.0.0.1:3333 #TODO Change proxy_pass port

#Install logstash
- hosts: servers
  roles:
    - role: valentinogagliardi.logstash-role

      logstash_defaults: |
        LS_USER=root
        LS_HEAP_SIZE="256m"
        LS_OPTS="--auto-reload --reload-interval 2"

      logstash_patterns: |
        TIMESTAMP_FOO %{MONTHDAY}-%{MONTH}-%{YEAR}-%{HOUR}:%{MINUTE}:%{SECOND}

      logstash_inputs: |

        jdbc {
          jdbc_connection_string => "jdbc:postgresql://localhost:5432/mydb"
          jdbc_user => "postgres"
          jdbc_validate_connection => true
          jdbc_driver_library => "/path/to/postgresql-9.4-1201.jdbc41.jar"
          jdbc_driver_class => "org.postgresql.Driver"
          statement => "SELECT * from contacts"
          }


      # logstash_filters: |
      #   geoip { source => "ip_address"
      #        }
      #
      #   multiline { pattern => "^No lfn2pfn"
      #              what => "previous"
      #            }

      logstash_outputs: |
        elasticsearch {
          protocol => http
          index => "contacts"
          document_type => "contact"
          document_id => "%{uid}"
          host => "ES_NODE_HOST"
        }
